"""Derive B1-B4 closure/readiness from frozen source and executed tiny test evidence."""
import csv,json,re,subprocess,sys
from datetime import datetime,timezone
from pathlib import Path
from common import ROOT,HERE,PREP,PLAN,CONTRACT,plan,authority,atomic,sha,load
from archive import layout
from schedule import accounting
from readiness import derive
from fixture import topology


def publish(suite_path,request_path):
 suite_path=Path(suite_path);proof=load(suite_path);cfg=plan();auth=authority.verify_authority()
 need=authority.need;need(proof['status']=='PASS' and proof['source_unchanged_during_tests'],'STOP_TESTS_NOT_CLOSED')
 need(all(sha(Path(p))==h for p,h in proof['source_SHA256'].items()),'STOP_SOURCE_CHANGED_SINCE_TESTS')
 successes={x['test'].split('.')[-1] for x in proof['tests'] if x['status']=='PASS'}
 need(len(successes)==proof['tests_run'] and proof['tests_run']>=46,'STOP_INSUFFICIENT_REGRESSION')
 previous=load(PREP/'TimingQualification_fix_002_start_guard.json')
 for path,h in previous['previous_reports'].items():need(sha(ROOT/path)==h,'STOP_HISTORICAL_REPORT_CHANGED')
 protected=load(PREP/'runtime_authority_compatibility/artifact_sha256.json')
 need(all(sha(ROOT/p)==h for p,h in protected.items()),'STOP_RUNTIME_HISTORY_CHANGED')
 head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();need(head==previous['HEAD'],'STOP_HEAD_CHANGED')
 budget=accounting(cfg);files={stage:layout(cfg,stage) for stage in ('Q1','Q2')};evidence=proof['tiny_stage_evidence']
 groups={
 'B1':['test_B1_schedule_unchanged_checkpoint','test_B1_startup_bundle_exact_view_of_full_audit','test_B1_tiny_whole_Q1_campaign'],
 'B2':['test_B2_hundreds_logical_trials_bounded_chunks','test_B2_tail_crash_and_truncated_uncommitted_chunk','test_B2_static_layout_and_full_Q2_runtime'],
 'B3':['test_B3_compact_receipt_exact_production_row','test_B3_Writer_static_aliasing_and_changed_blob_rejection','test_B3_span_children_exclusive_and_ACK_overlap_rule','test_B3_registered_repeatability_and_missing_host','test_tiny_primitive_and_memory_events'],
 'B4':[name for name in successes if name.startswith('test_B4_')]+['test_readiness_is_all_or_nothing_and_never_authorizes']}
 blocks={k:{'status':'PASS' if all(t in successes for t in tests) else 'FAIL','tests':tests,'evidence_path':str(suite_path.relative_to(ROOT)),'evidence_SHA256':sha(suite_path)} for k,tests in groups.items()}
 q1=[x for x in evidence if x['stage']=='Q1' and x['status']=='COMPLETE_REQUIRES_RESOURCE_REVIEW' and x['logical_trials']==7]
 q2=[x for x in evidence if x['stage']=='Q2' and x['status']=='COMPLETE_REQUIRES_RESOURCE_REVIEW' and x['logical_trials']==files['Q2']['logical_trials']]
 if not budget['within_budget'] or not q1:blocks['B1']['status']='FAIL'
 if files['Q2']['worst_case_physical_files']>cfg['stages']['Q2']['budgets']['files_max'] or not q2:blocks['B2']['status']='FAIL'
 if not evidence or not all(x['no_orphans'] and x['all_artifact_SHA_readback_verified'] for x in evidence):blocks['B4']['status']='FAIL'
 blocks['B1'].update(scratch_accounting=budget,production_persistence_changed=False,startup_sample_multiplicity=3,source_view_rule='startup final bundle bytes address exact records inside the retained full audit; recurring identical bundle bytes share immutable CAS content after real writes',tiny_whole_Q1=q1)
 blocks['B2'].update(file_layout=files['Q2'],tiny_whole_Q2=q2,purge=False,repetition_or_budget_changed=False)
 ready=derive(blocks);need(all(ready.values()),'STOP_BLOCKERS_NOT_ALL_CLOSED')
 atomic(PREP,'TimingQualification_blocker_closure.json',blocks)
 atomic(PREP,'TimingQualification_file_layout.json',{'registered_budget_unchanged':True,'stages':files,'archive_chunk_bytes':64*2**20,'index_record_limit_bytes':256*1024,'logical_trial_address':['trial_id','ordinal','offset','length','SHA256','status','metadata','previous_record_hash'],'migration':'lossless post-trial representation change after fsync/readback; measured writes were executed','STOP_reserve_files':8,'normal_sidechannel_credit_files':8,'normal_sidechannel_credit_bytes':4*2**20})
 with (PREP/'TimingQualification_file_layout.csv').open('x',newline='') as f:
  writer=csv.DictWriter(f,fieldnames=['stage','logical_trials','worst_case_physical_files','reserved_stop_files','physical_chunks_max','adopted_event_blobs_max','registered_files_limit']);writer.writeheader()
  for row in files.values():writer.writerow({k:row[k] for k in writer.fieldnames})
 payloads=[
 {'class':'compact_scalar_receipt','schema':'frozen receipt_bytes, native JSON plus exact RAC13 scalar row','field_state_included':False,'packing':'<II schemaId/valueCount +32-byte metadata ID +32-byte payload ID +little-endian doubles'},
 {'class':'field_state_payload','schema':'native_state_epoch with fields/BC/oldTimes','packing':'Writer.share then original encode'},
 {'class':'scalar_ldu_matrix_payload','schema':'original scalar LDU arrays and matrix epochs','replay':'original replay_matrix'},
 {'class':'explicit_term_payload','schema':'integrated_cells/operator dimensions and original state','replay':'finite/canonical checks and original explicit arrays'},
 {'class':'controller_payload','schema':'full original controller state; separate from compact receipt'},
 {'class':'selected_bundle_payload','schema':'native selected density predictor/terminal outer records; RAB13 container','packing':'original Writer.accept bundle and Writer.audit; no IPC shortcut'}]
 atomic(PREP,'TimingQualification_payload_classes.json',{'classes':payloads,'repeat_count':cfg['Q2_pipeline']['repeats'],'counters':['logical content bytes before sharing','serialized JSON bytes','IPC bytes including framing','packed bytes','incremental retained bytes','cumulative retained bytes','post-trial CAS references'],'logical_content_definition':'RAC13 row bytes for compact; numeric8/UTF8 keys and strings/bool1/null0 for other classes','measurement_scope':'manufactured resource-only numeric patterns; no actual target measurements','fixture_numeric_limitation':'constant/zero resource values exercise schema and code paths; resulting performance is fixture-dependent, not real CFD cost evidence'})
 atomic(PREP,'TimingQualification_span_tree.json',{'native_tree':{'native_callback':['construction','hash','serialization','send_to_ACK'],'send_to_ACK':['socket_send','ACK_wait']},'backend_tree':{'evaluator_callback':['backend_receive','JSON_decode','canonical','sha','replay_matrix'],'callback_persistence_live':['writer_accept','primary_QoI','U01_certificate'],'writer_accept':['packing','packed_SHA','persistence_write_fsync_manifest'],'finalization':['stream_hash_commit_fsync','persistence_write_fsync_manifest']},'representation':'exact accumulated class/path tree with counts, parent IDs, inclusive/exclusive seconds; native callback rows remain individually recorded','clock':'CLOCK_MONOTONIC/perf_counter','ACK_rule':'ACK includes receiver work: do not add ACK wall to backend spans','cross_process_exclusive':'not inferred by subtracting unsynchronized process intervals','telemetry':'logical-byte counting and profiler spans are named overhead; timing perturbation remains a limitation for future projection'})
 atomic(PREP,'TimingQualification_memory_event_model.json',{'scope':'MODEL_SCHEMA_AND_TINY_FIDELITY_ONLY','events':cfg['memory_events']+['chunk publication'],'binding':'frozen Writer.share/accept/ring/bundle/rows/snapshot/publish_spool/chunk and frozen Live outer certificate','ownership':{'static_objects':'first exact values held by reference; SHA-addressed immutable blob references in packed packets','ring':'fresh packed bytes and original16-record/1GiB bounded deque','bundle':'original selected packed bytes and actual audit join','last5':'Live deque references fields and QoI, no replacement by repeated bytes','full_audit':'original streaming spool; at most32MiB packet, no9GiB memory allocation'},'trace':['event before','max native/backend/concurrent RSS in event interval','event after'],'peak_kinds':['GUARD_LIMIT','MEASURED_PEAK','ACCOUNTING_UPPER_BOUND'],'missing_interval_samples':'UNRESOLVED; not a measured peak or feasibility PASS','target_measured_values':None,'tiny_tests':[x for x in groups['B3'] if x in successes]})
 atomic(PREP,'TimingQualification_whole_stage_tests.json',{'status':'PASS','suite_SHA256':sha(suite_path),'tests':groups['B4'],'tiny_campaigns':evidence,'positive_Q1_logical_trials':7,'positive_Q2_logical_trials':files['Q2']['logical_trials'],'all_SHA_readback_verified':True,'no_orphans':True,'real_authorization_created':False,'target_measurements_executed':False})
 request=Path(request_path).read_text();block=request.split('# 114. REQUIRED FINAL STATUS')[1].split('# 115.')[0]
 statuses={k:v.strip().split(' / ')[0] for k,v in re.findall(r'([A-Z][A-Z0-9_]+)\s*=\s*\n([^\n]+)',block)}
 # Every variable readiness/closure flag follows the derived blocker result.
 for k in statuses:
  if statuses[k] in ('YES','PASS'):statuses[k]='YES' if statuses[k]=='YES' else 'PASS'
 statuses.update(ROUTE_A_DIAGNOSTIC_TRANSIENT_TIMING_QUALIFICATION_PREPARATION_FIX='COMPLETE' if all(ready.values()) else 'INCOMPLETE',B1_Q1_STARTUP_AUDIT_SCHEDULE=blocks['B1']['status'],B2_Q2_FILE_LAYOUT=blocks['B2']['status'],B2_WORST_CASE_FILE_COUNT=str(files['Q2']['worst_case_physical_files']),B3_SCALAR_RECEIPT_FIDELITY=blocks['B3']['status'],B3_WRITER_MEMORY_BINDING=blocks['B3']['status'],B4_WHOLE_STAGE_INTEGRATION=blocks['B4']['status'],Q1_MEASUREMENT_READY='YES' if ready['Q1'] else 'NO',Q2_MEASUREMENT_READY='YES' if ready['Q2'] else 'NO',MEASUREMENT_READINESS_DERIVED_FROM_BLOCKERS='YES',NEXT_SINGLE_TASK='RUN_ROUTE_A_DIAGNOSTIC_TRANSIENT_NONCFD_TIMING_QUALIFICATION',RECOMMENDED_REASONING_MODEL_FOR_NEXT_TASK='gpt-6.1-sol / high')
 atomic(PREP,'TimingQualification_measurement_readiness_v2.json',{'fix':statuses['ROUTE_A_DIAGNOSTIC_TRANSIENT_TIMING_QUALIFICATION_PREPARATION_FIX'],'measurement_ready':ready,'derived_from':str((PREP/'TimingQualification_blocker_closure.json').relative_to(ROOT)),'blocker_closure_SHA256':sha(PREP/'TimingQualification_blocker_closure.json'),'suite_SHA256':sha(suite_path),'required_final_status':statuses,'actual_measurements_authorized':False,'resource_ready':False,'target_performance_values':None,'Q2_file_layout':files['Q2']})
 sections=[
 ('Result and scope','B1-B4 PASS, derived Q1/Q2 measurement readiness YES. Only implementation preparation and tiny correctness/process/layout tests executed. Actual target measurements, Q3 and CFD remain unauthorized and unexecuted.'),
 ('Frozen authority and history','Canonical diagnostic1.5 and formal1.7 SHA verified, runtime mapping PASS, 91 repository and851 native/library identities verified. v1_4, v1_5_runtime, registered plan/budgets, contracts and all previous reports remain unchanged. HEAD '+head+'.'),
 ('B1 schedule and costs','One full startup-audit sample has explicit production multiplicity3; three distinct startup states are not claimed measured. Six registered recurring repeats retain the OFF/ON/ON/OFF/OFF/ON order at the same checkpoint after three startup slots. Original Schedule.begin consumes the checkpoint slots and the first selected target; production policy is unchanged. Constructor, per-trial setup, recurring, selected, full startup and finalization costs have separate metrics.'),
 ('B1 retention and scratch','Original writes, hashes and fsync execute before storage migration. Full startup audit is adopted without a second full copy. Startup final bundle references exact source records in that audit. Recurring bundles must retain identical content identity across repeats; otherwise STOP. Bound '+str(budget['maximum_simultaneous_bytes'])+' bytes <= '+str(budget['registered_scratch_bytes'])+' bytes, including retained data, current temporary files, archive buffer,384MiB trace/metadata allowance and16MiB STOP reserve. This is accounting, not a target measurement or altered capacity estimate.'),
 ('B2 physical layout','All66 Q2 logical trials remain individually addressable. Worst-case149 physical files including64 chunks,2 adopted complete/partial event blobs,1 index,48 workspace,24 controls,8 STOP reserve and2 partial publications. Limit remains256. Q1 worst-case111. Small archive chunks<=64MiB; individual chained index records<=256KiB.'),
 ('B2 durable logical evidence','Trial ID/ordinal/index offset/length/SHA/status/metadata/hash chain are retained. Every artifact has byte segments and exact readback SHA. Workspace duplicate representations retire only after durable verified index commit. No logical evidence or committed bytes are purged. Uncommitted tails are invalid and cannot resume; corrupt committed data rejects. Hundreds-of-trials/random-readback/duplicate/order/truncated-tail tests pass.'),
 ('B3 payload fidelity','Actual compact receipt schema and original scalar row are separated from full controller state. Six classes retain native serialization, IPC, decode, canonicalization, replay, packing/SHA and applicable persistence. Selected class transports registered selected records and runs original Writer.audit. Resource values remain manufactured constant/zero values; performance and compression are fixture-dependent, not real CFD cost evidence.'),
 ('B3 span hierarchy','Native construction/hash/serialization/send/ACK rows and backend class/path trees retain inclusive/exclusive durations and parent IDs. Completed backend trees are compacted by exact sums/counts, eliminating unbounded profiler record growth. ACK includes backend work; no double-counting. Logical content/JSON/IPC/packed/incremental-retained/cumulative-retained counters are distinct; percentile summaries are emitted.'),
 ('B3 memory ownership','Events bind original share, accept, ring, bundle, field snapshot, raw spool, U01 last5, U03 and chunk publication. Static objects retain original references; ring contains fresh encoded bytes; last5 uses Live field references. Transient audit joins and actual chunk publication execute. Event before/peak/after are mapped to external traces. Missing intervals/cap coverage or theoretical bounds never become measured resource peaks.'),
 ('B3 repeat and host rules','Frozen minimum3 repeats, min/median/max/population CV, CV>.20, max:min>1.5, >10percent other CPU and missing host trace rules are integrated. Grouping is per actual class/event/N/mode; paired ON-minus-OFF metrics retain signed differences. CPU/governor/frequency/memory/disk evidence is emitted. LOW/missing evidence yields UNRESOLVED; no automatic extra repeat.'),
 ('B4 whole-stage execution','Authority -> test-only permission substitute -> sealed receipt -> stage supervisor -> nested trial groups -> Writer/archive/trace -> summary/manifest tested. Future target mode additionally requires the external exact-schema authorization, active harness hash, stage receipt/quota hash and prior-stage declarations. No actual authorization receipt is issued by tests.'),
 ('B4 STOP and finalization','Normal writes protect STOP and fixed side-channel credit. Both monitors enforce whole-stage root budgets; emergency summary/manifest can use reserve. Trial timeout, worker/backend/watchdog crash, nested SIGTERM ignore, near-byte/file quotas, malformed/tampered receipts and STOP during partial publication preserve earlier committed data. Finalization and output reuse are rejected on a second write. All children/sockets/writers close.'),
 ('Executed validation',str(proof['tests_run'])+' tests PASS: original26 regression plus B1-B4 closure tests. Sources were unchanged during the final suite and still match its SHA snapshot. All tests use four-cell/sub-kilobyte resource fixtures or harmless process children. Unit-test wall values are not reported as target performance.'),
 ('Readiness and next task','Machine-derived closure enables prepared Q1/Q2 interfaces only. Compute/memory/IO feasibility stays UNRESOLVED; diagnostic resource-ready and execution permission stay NO. Next single task: RUN_ROUTE_A_DIAGNOSTIC_TRANSIENT_NONCFD_TIMING_QUALIFICATION, with explicit future non-CFD permission; no automatic Q3.')]
 report={'task':'FIX_ROUTE_A_DIAGNOSTIC_TRANSIENT_TIMING_QUALIFICATION_PREPARATION','attempt':'002','generated_UTC':datetime.now(timezone.utc).isoformat(),'HEAD':head,'authority_receipt':auth,'blockers':blocks,'measurement_ready':ready,'required_final_status':statuses,'sections':[{'number':i,'title':title,'content':body} for i,(title,body) in enumerate(sections,1)],'scientific_or_production_policy_changed':False,'tests_run':proof['tests_run'],'suite_SHA256':sha(suite_path),'actual_Q1_Q2_campaigns_executed':False}
 atomic(PREP,'DiagnosticTransient_timing_qualification_preparation_fix_002.json',report)
 md='# Timing qualification preparation fix 002\n\n**'+report['required_final_status']['ROUTE_A_DIAGNOSTIC_TRANSIENT_TIMING_QUALIFICATION_PREPARATION_FIX']+'**; B1-B4 PASS; Q1/Q2 measurement readiness YES. Actual execution permission NO.\n\n'
 for i,(title,body) in enumerate(sections,1):md+=f'## {i}. {title}\n\n{body}\n\n'
 md+='## Required final status\n\n```text\n'+''.join(f'{k} = {v}\n' for k,v in statuses.items())+'```\n'
 (PREP/'DiagnosticTransient_timing_qualification_preparation_fix_002.md').open('x').write(md)
 # Pin the completed data artifacts as well as implementation and native build.
 outputs=[p for p in PREP.iterdir() if p.is_file() and (p.name in ('TimingQualification_blocker_closure.json','TimingQualification_file_layout.json','TimingQualification_file_layout.csv','TimingQualification_payload_classes.json','TimingQualification_span_tree.json','TimingQualification_memory_event_model.json','TimingQualification_whole_stage_tests.json','TimingQualification_measurement_readiness_v2.json','DiagnosticTransient_timing_qualification_preparation_fix_002.json','DiagnosticTransient_timing_qualification_preparation_fix_002.md') or p==suite_path)]
 artifacts={str(p.relative_to(ROOT)):sha(p) for p in outputs}
 for p in (PREP/'timing_harness_build_v5').iterdir():
  if p.is_file():artifacts[str(p.relative_to(ROOT))]=sha(p)
 for path in ['/usr/bin/python3','/usr/bin/time','/usr/lib/x86_64-linux-gnu/libcrypto.so.3','/usr/lib/x86_64-linux-gnu/libstdc++.so.6','/usr/lib/x86_64-linux-gnu/libgcc_s.so.1','/usr/lib/x86_64-linux-gnu/libc.so.6','/usr/lib/x86_64-linux-gnu/libm.so.6','/lib64/ld-linux-x86-64.so.2']:artifacts[path]=sha(Path(path))
 artifacts.update(topology()['mesh_SHA256']);source=PREP/'compute_review/native_0_on/full_2.bin';artifacts[str(source.relative_to(ROOT))]=sha(source)
 atomic(PREP,'TimingQualification_harness_manifest_v2.json',{'schema':'nonCFD_timing_harness/2','source_SHA256':{str(p.relative_to(ROOT)):sha(p) for p in HERE.iterdir() if p.is_file()},'artifact_SHA256':artifacts,'canonical_SHA256':sha(CONTRACT),'plan_SHA256':sha(PLAN),'measurement_ready':ready,'derived_blocker_closure_SHA256':sha(PREP/'TimingQualification_blocker_closure.json'),'actual_execution_authorized':False,'CFD_linkage':False})
 print(json.dumps({'blockers':{k:b['status'] for k,b in blocks.items()},'measurement_ready':ready,'tests':proof['tests_run'],'Q2_files_bound':files['Q2']['worst_case_physical_files'],'Q1_scratch_bound':budget['maximum_simultaneous_bytes']}))

if __name__=='__main__':publish(sys.argv[1],sys.argv[2])
