"""Fresh per-class accounting; no relabeling permanent selected evidence as TEMP."""
import csv,json,os
from pathlib import Path
H=Path(__file__).resolve().parent;R=H.parents[3];PREP=R/'results/routeA/diagnostic_transient/diagnostic_attempt_001/preparation';OUT=PREP/'resource_revision_fix'

def calculate():
    old=json.loads((PREP/'resource_revision/capacity_accounting.json').read_text());free=json.loads((OUT/'start_guard.json').read_text())['free_bytes_at_start'];scratch=16*2**30;rows=[];series={}
    for se in old['scenarios'][-1]['series']:
        parts=dict(se['parts']);parts['receipts_and_primary']+=se['steps']*(64*2**10-old['primary_reserve_bytes_per_step'])
        categories={'R0':sum(parts[k] for k in ('receipts_and_primary','complete_solver_logs','fixed_provenance_and_static')),'R1':parts['full_raw_audits']+parts['selected_bundles'],'R2':parts['field_snapshots'],'R3_R4_shared_cap':scratch}
        permanent=sum(categories[k] for k in ('R0','R1','R2'))
        series[se['Co']]={'Co':float(se['Co']),'steps_planning_only':se['steps'],'permanent_bytes':permanent,'working_peak_bytes':permanent+scratch,'reclaimable_upper_bound_bytes':scratch,'reclaimable_actual_bytes':'MEASURE_SEALED_ALLOWLIST; not a guaranteed16GiB reclaim','file_bound':se['file_count_bound']+se['receipt_chunks']+64,'parts':parts,'retention_bytes':categories}
        for k,value in categories.items():rows.append({'Co':se['Co'],'category':k,'during_run_bytes':value,'post_seal_bytes':value if k!='R3_R4_shared_cap' else 0,'purge_eligible_bytes_upper_bound':value if k=='R3_R4_shared_cap' else 0,'permanent_bytes':value if k!='R3_R4_shared_cap' else 0})
    for co in series:
        for cls,definition in [('R3','Nonselected validation/conversion copies until seal'),('R4','Scratch/rolling/atomic/replay workspace')]:
            rows.append({'Co':co,'category':cls,'during_run_bytes':'MEASURE_ACTUAL; R3+R4 jointly<=17179869184','post_seal_bytes':0,'purge_eligible_bytes_upper_bound':'MEASURE_SEALED_ALLOWLIST; shared joint cap above','permanent_bytes':0})
    A=series['0.5']['permanent_bytes'];B=series['0.25']['permanent_bytes'];C=series['0.125']['permanent_bytes']
    seq=[{'stage':'Co0.5 running','existing_permanent_bytes':0,'current_working_bytes':A+scratch,'peak_total_bytes':A+scratch},{'stage':'Co0.5 sealed','existing_permanent_bytes':A,'current_working_bytes':scratch,'peak_total_bytes':A+scratch},{'stage':'Co0.5 purged','existing_permanent_bytes':A,'current_working_bytes':0,'peak_total_bytes':A},{'stage':'Co0.25 running','existing_permanent_bytes':A,'current_working_bytes':B+scratch,'peak_total_bytes':A+B+scratch},{'stage':'Both sealed/purged','existing_permanent_bytes':A+B,'current_working_bytes':0,'peak_total_bytes':A+B},{'stage':'Co0.125 possible','existing_permanent_bytes':A+B,'current_working_bytes':C+scratch,'peak_total_bytes':A+B+C+scratch}]
    result={'classification':'PLANNING_CAPS_NOT_PRODUCTION_MEASUREMENT','free_bytes_at_start':free,'series':series,'primary_permanent_bytes':A+B,'sequential_primary_peak_bytes':A+B+scratch,'sequential_primary_peak_fraction_of_free':(A+B+scratch)/free,'Co0125_post_purge_peak_bytes':A+B+C+scratch,'Co0125_post_purge_peak_fraction_of_free':(A+B+C+scratch)/free,'three_series_models':{'A_all_unpurged_upper_bound':A+B+C+3*scratch,'B_Co05_purged_upper_bound':A+B+C+2*scratch,'C_both_purged_upper_bound':A+B+C+scratch},'safety_policy':'per-series current free > current peak + existing permanent (additional conservative reserve) + max32GiB,10percent current free; free already excludes existing footprint, do not double-count in actual peak totals','scratch_policy':'All R3 validation copies + R4 spools/replay share16GiB; nonselected raw is evaluated then discarded online and has no on-disk reclaim credit','R2_policy':'Inherited selection schedule including505 upper-bound snapshots, initial/final and64 trigger reserve remain permanent; arrival crossing capture included in reserve','primary_scalar_cap_bytes_per_step':65536,'old_candidate_primary_scalar_reserve_bytes_per_step':8192,'projection_note':'Old394GB was main TWO-series total, not one-series permanent. New64KiB row cap explicitly includes169 linear component records + U01/U03/scalars. R1 selected audits were re-summed, never marked deletable. Live context adds small residual metadata; full/bundle caps have slack above old6.53GB/.331GB projections. Static geometry context covered by1GiB fixed reserve.','storage_feasibility_primary':'FEASIBLE_UNDER_PLANNING_CAPS','storage_feasibility_Co0125':'INFEASIBLE_AT_TSTAR2_ON_CURRENT_DISK_EVEN_AFTER_PRIOR_PURGE','production_measurement_unresolved':True}
    (OUT/'lifecycle_capacity.json').write_text(json.dumps(result,indent=2)+'\n')
    for name,data in [('DiagnosticTransient_retention_classes.csv',rows),('DiagnosticTransient_sequential_storage_model.csv',seq)]:
        with (PREP/name).open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(data[0]));w.writeheader();w.writerows(data)
    return result
if __name__=='__main__':print(json.dumps(calculate(),indent=2))
