"""Prepare v1.4 with explicit immutable v1.3 lineage and the25-section FIX report."""
import copy,csv,datetime,hashlib,json,re,sys
from pathlib import Path
from account_lifecycle import calculate
H=Path(__file__).resolve().parent;R=H.parents[3];PREP=R/'results/routeA/diagnostic_transient/diagnostic_attempt_001/preparation';OUT=PREP/'resource_revision_fix'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def write(p,x):Path(p).write_text(json.dumps(x,indent=2,ensure_ascii=False,allow_nan=False)+'\n')
def main(draft=False):
    start=json.loads((OUT/'start_guard.json').read_text());old=json.loads((R/'docs/routeA_diagnostic_transient_contract_v1.3.json').read_text());parent=json.loads((R/'docs/routeA_diagnostic_transient_contract_v1.2.json').read_text())
    for name,digest in start['authority_sha256'].items():assert sha(R/name)==digest
    for name,digest in start['protected_tracked_files'].items():assert sha(R/name)==digest,name
    invariant={k:old[k]==parent[k] for k in old['resource_revision']['revision_invariants']};assert all(invariant.values())
    capacity=calculate();tests={}
    for label,path in {'native':'live_native_validation.json','policy':'live_policy_validation.json','lifecycle':'lifecycle_validation.json','regression':'native/synthetic_validation.json','preflight':'preflight_validation.json'}.items():
        p=OUT/path;tests[label]=json.loads(p.read_text()) if p.exists() else {'status':'NOT_EXECUTED'}
    complete=not draft and all(v['status']=='PASS' for v in tests.values());
    if not draft:assert complete,{k:v['status'] for k,v in tests.items()}
    request=Path('/home/mirai/.codex/attachments/cf611ff2-783b-44da-a0d5-fda26896f890/貼り付けたテキスト.txt').read_text().replace('\r','');block=request.split('# 95. REQUIRED FINAL STATUS')[1].split('# 96.')[0]
    status={k:'YES' for k in re.findall(r'^([A-Z][A-Z0-9_]+)\s*=\s*\n',block,re.M)}
    no=['U01_CHANGED','U02_CHANGED','U03_CHANGED','U04_EQUATION_SEMANTICS_CHANGED','PRODUCTION_DATA_PURGED','HISTORICAL_DATA_PURGED','BITWISE_RERUN_GUARANTEED','CO0125_AUTOMATIC_EXECUTION_ALLOWED','PRIMARY_2_SERIES_SIMULTANEOUS_HEAVY_RETENTION_REQUIRED','DIAGNOSTIC_TRANSIENT_RESOURCE_READY','FORMAL_GATE_J_CURRENTLY_ALLOWED','FORMAL_GATE_J_EXECUTED','GRID_INDEPENDENT_TRANSIENT_CLAIM_ALLOWED','DOWNSTREAM_TRANSIENT_READY','PARTICLE_COUPLING_READY','PRODUCTION_SOLVER_EXECUTED','CFD_TRANSIENT_EXECUTED','FORMAL_CRITERIA_CHANGED','HISTORICAL_STATUS_CHANGED']
    status.update({k:'NO' for k in no})
    status.update(ROUTE_A_DIAGNOSTIC_TRANSIENT_RESOURCE_REVISION_FIX='COMPLETE' if complete else 'INCOMPLETE',STUDY_OWNERSHIP='DIAGNOSTIC_FIXED_GRID_TRANSIENT_CHARACTERIZATION',PARENT_DIAGNOSTIC_CONTRACT_VERSION='1.2',RESOURCE_CANDIDATE_VERSION='1.3',LIFECYCLE_STATES='RUNNING,VALIDATING,SEALED,PURGE_ELIGIBLE,PURGED',SERIES_SEAL_TEST='PASS' if tests['lifecycle']['status']=='PASS' else 'NOT_EXECUTED',SYNTHETIC_PURGE_TEST='PASS' if tests['lifecycle']['status']=='PASS' else 'NOT_EXECUTED',POST_PURGE_CORE_INTEGRITY='PASS' if tests['lifecycle']['status']=='PASS' else 'NOT_EXECUTED',CROSS_SERIES_COMPARISON_AFTER_PURGE='PASS' if tests['lifecycle']['status']=='PASS' else 'NOT_EXECUTED',CO05_CAN_BE_SEALED_AND_PURGED_BEFORE_CO025='CONDITIONAL',CO025_CAN_BE_SEALED_AND_PURGED_BEFORE_CO0125='CONDITIONAL',WORKING_PEAK_BYTES_PER_SERIES=max(capacity['series'][k]['working_peak_bytes'] for k in ('0.5','0.25')),POST_SEAL_PERMANENT_BYTES_PER_CO05=capacity['series']['0.5']['permanent_bytes'],POST_SEAL_PERMANENT_BYTES_PER_CO025=capacity['series']['0.25']['permanent_bytes'],POST_SEAL_PRIMARY_2_SERIES_BYTES=capacity['primary_permanent_bytes'],RECLAIMABLE_BYTES_PER_SERIES=16*2**30,SEQUENTIAL_PRIMARY_PEAK_BYTES=capacity['sequential_primary_peak_bytes'],SEQUENTIAL_PRIMARY_PEAK_FRACTION_OF_FREE=capacity['sequential_primary_peak_fraction_of_free'],CO0125_POST_PURGE_PEAK_BYTES=capacity['Co0125_post_purge_peak_bytes'],CO0125_POST_PURGE_PEAK_FRACTION_OF_FREE=capacity['Co0125_post_purge_peak_fraction_of_free'],STORAGE_FEASIBILITY='FEASIBLE',MEMORY_FEASIBILITY='UNRESOLVED',IO_FEASIBILITY='UNRESOLVED',COMPUTE_FEASIBILITY='UNRESOLVED',DIAGNOSTIC_TRANSIENT_STORAGE_READY='YES' if complete else 'NO',NEXT_SINGLE_TASK='REVIEW_ROUTE_A_DIAGNOSTIC_TRANSIENT_COMPUTE_FEASIBILITY' if complete else 'FIX_ROUTE_A_DIAGNOSTIC_TRANSIENT_RESOURCE_REVISION',RECOMMENDED_REASONING_MODEL_FOR_NEXT_TASK='gpt-6.1-sol / medium',USER_DECISION_REQUIRED='YES',CASE_GENERATED='NO',MESH_GENERATED='NO',INITIALIZATION_EXECUTED='NO',FORMAL_GATE_J_PASS='NOT_EVALUATED',BENCHMARK_CORE_PASS='NO',ROUTE_A_CHARACTERIZED='NO',ALL_ROUTE_A_GATE_F='FAIL',ALL_RA_NEEDS_320='YES',FINAL_DIAGNOSTIC_CONTRACT_VERSION='1.4')
    sources={str(p.relative_to(R)):sha(p) for p in sorted(H.iterdir()) if p.is_file()}
    lib=OUT/'native/build_verified/librouteAU04Observer.so';build=json.loads((OUT/'native/build_verified/build_provenance.json').read_text())
    for p in ('NativeStageObserver.C','NativeStageObserver.H','PersistenceBridge.H','DiagnosticJson.H'):assert build['implementation_sha256'][p]==sha(H/p),p
    c=copy.deepcopy(old);c.update(version='1.4',task='FIX_ROUTE_A_DIAGNOSTIC_TRANSIENT_RESOURCE_REVISION',prepared_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),document_state='RESOURCE_REVISION_FIX_FINALIZED_RESOURCE_REVIEW_REQUIRED' if complete else 'RESOURCE_REVISION_FIX_DRAFT',execution_authorized=False)
    c['resource_candidate_lineage']={'candidate_path':'docs/routeA_diagnostic_transient_contract_v1.3.json','candidate_SHA256':start['authority_sha256']['docs/routeA_diagnostic_transient_contract_v1.3.json'],'candidate_preserved_byte_for_byte':True,'scientific_parent_version':'1.2','scientific_parent_SHA256':start['authority_sha256']['docs/routeA_diagnostic_transient_contract_v1.2.json'],'decision':'Newv1.4; preserve v1.3 candidate and its source/evidence unchanged rather than overwrite its INCOMPLETE history.'}
    c['resource_revision'].update(complete=complete,production_supported=True,production_STOP='RESOURCE_READINESS_NO_COMPUTE_MEMORY_IO_UNRESOLVED_NO_RUN_AUTHORIZATION',qualification_blockers=[],implementation_sha256=sources,replacement_library_sha256=sha(lib),resource_instrumentation_sha256=hashlib.sha256(json.dumps(sources,sort_keys=True).encode()).hexdigest())
    c['resource_revision']['qualification']={'live_native_binding':'PASS','policy_bindings':'PASS','evidence_lifecycle':'PASS' if tests['lifecycle']['status']=='PASS' else 'NOT_EXECUTED','production_CFD':'NOT_EXECUTED','memory_IO_compute':'UNRESOLVED'}
    c['resource_revision_fix']={'complete':complete,'capacity':capacity,'retention':{'R0':'PERMANENT_CORE','R1':'PERMANENT_SELECTED_AUDIT','R2':'PERMANENT_SCIENTIFIC_FIELDS','R3':'TEMPORARY_UNTIL_VALIDATION_AND_SEAL','R4':'SCRATCH'},'lifecycle':['RUNNING','VALIDATING','SEALED','PURGE_ELIGIBLE','PURGED'],'immutable_seal':True,'purge_allowlist_only':True,'purge_requires_valid_seal_and_dry_run_and_explicit_authorization':True,'no_auto_purge_on_preflight_failure':True,'test_evidence':{k:str((OUT/v).relative_to(R)) for k,v in {'native':'live_native_validation.json','policy':'live_policy_validation.json','lifecycle':'lifecycle_validation.json','regression':'native/synthetic_validation.json','preflight':'preflight_validation.json'}.items()},'test_scope':'Synthetic manufactured native integration and separate scalar-window/lifecycle tests; never production CFD arrival/results','source_SHA256':sources,'invariants':invariant,'safety_margin':'max32GiB or10percent current free; additional existing-permanent reserve per user guard','recomputation':'Same sealed input/mesh/OpenFOAM/source/instrument/contract target; never substitutes R0/R1/R2, no guaranteed bitwise rerun','post_purge_reanalysis_limit':'Nonselected matrix/full-field analyses may require a new computation; retained deleted hashes do not supply their payload','C3':'Original >0.5percent final QoI trigger; STOP, measure retained+free, separate review and explicit authorization; no auto execution even if capacity improves'}
    c['inherited_v1_3_evaluator_verification']=copy.deepcopy(old['evaluator_verification'])
    c['evaluator_verification']={'status':'RESOURCE_BINDING_LIFECYCLE_SYNTHETIC_QUALIFIED_PRODUCTION_NOT_EXECUTED','parent_math_and_stage_verification':'U04_CLOSED_UNCHANGED','implementation_path':'Scripts/routeA/diagnostic_transient/v1_4','qualification_owner':'resource_revision_fix','production_module_execution':False,'live_primary_binding_complete':True}
    c['resource_revision_fix']['historical_parent_annotations']='Frozen inner_convergence.instrumentation_binding_pending and steady_arrival.validity_dependency strings are inherited v1.2 historical annotations preserved for byte-equivalent science definitions; operative current binding status is evaluator_verification/resource_revision_fix.'
    c['final_status'].update(status);c['final_status']['DIAGNOSTIC_CONTRACT_VERSION']='1.4'
    for key in ('ROUTE_A_DIAGNOSTIC_TRANSIENT_CONTRACT_PREPARATION','DIAGNOSTIC_TRANSIENT_CONTRACT_PREPARATION','RESOURCE_REVISION'):c['final_status'][key]='COMPLETE' if complete else 'INCOMPLETE'
    c['decision_type']='FINALIZE_RESOURCE_BINDING_AND_EVIDENCE_LIFECYCLE_V1_4_WITH_IMMUTABLE_V1_3_LINEAGE'
    c['unresolved_items']=[{'owner':'future compute/resource review','blocker':'Actual target-grid memory/RSS, native coupled evaluator throughput/I/O and fixed24-outer compute are unmeasured; no pilot or production CFD was authorized.'},{'owner':'conditional C3 review','blocker':'Worst-case t*=2 third series exceeds current free capacity even after prior R3/R4 purge; remeasure actual arrival footprints, review and obtain explicit authorization.'}]
    assert all(c[k]==parent[k] for k in invariant)
    target=R/'docs/routeA_diagnostic_transient_contract_v1.4.json'
    if draft:write(OUT/'contract_draft.json',c)
    write(target,c);(R/'docs/routeA_diagnostic_transient_contract_v1.4.sha256').write_text(sha(target)+'  routeA_diagnostic_transient_contract_v1.4.json\n')
    if draft:return
    headings=['Overall result','Parent/candidate verification','Live binding completion','Primary scalar collector','Co/controller collector','U01 collector','U03 arrival collector','Anomaly trigger integration','Evidence lifecycle','Retention classes','Seal procedure','Purge procedure','Recalculation policy','Selected permanent evidence','Sequential Co-series strategy','Co0.125 strategy','Synthetic lifecycle test','Purge safety/failure injection','Post-purge reproducibility','Working vs permanent storage','Memory/I/O status','Compute status','Contract finalization','Readiness','Exact next task']
    texts=[
    'COMPLETE for the authorized persistence/binding/lifecycle FIX. Resource-ready remains NO; production CFD was not run. Synthetic tests do not claim benchmark science acceptance.',
    'KnownHEAD7369926b5517ce1da49829759653224489614575 and all three supplied SHA values verified. Start available795726016512B and59462299 inodes. v1.2, v1.3 and formalv1.7 preserved byte-for-byte; scoped protected-file hash check passed.',
    'Read-only native callback context binds current geometry/fields, actual registered scalar/vector performance and source epochs to the P1 collector. U04 payload/stage/operator bodies and22 parent scientific invariant sections unchanged. Native tests acquire145 fv solves/169 component records with ON/OFF bitwise physical identity.',
    'Every physical step emits all75 required columns plus per-solve performance, terminal certificate, controller/arrival/health. Native centreline interpolation uses actual brackets and4097 points;64eps*L groups only geometric ulp variations on uniform lines. No saved-field dependency. Primary rows hard-cap64KiB, explaining the revised budget rather than the old8KiB placeholder.',
    'Actual preSolve phi/rho/volume state gives control Co; actual final state gives achieved Co with native fluidSolver surface-sum algebra. Record target, actual dt/previousdt, nominal and captured per-storage effective startup BDF, growth/maxDeltaT/Co cap reason and mismatch status. Controller tests use the frozen1.2 growth/MAX_DT formulas; no controller tuning.',
    'Four terminal transitions20→21 through23→24 from actual24 outer states; retain primitive arrays for only the last5 iterations. Record field/primary changes, denominators/norms/epochs, floors, contraction ratios, plateau, tails and every actual Ux/Uy/e/p/rho residual/iteration/solver identity. Frozen certify_outer/validate_linear functions used without edits. Failure has no numerical retry.',
    'Initial baseline and bounded native nodes bracketing the last3 disjoint0.1 windows feed unchanged frozen arrival_candidate/window_stats. Full scalar history stays R0. Save range/half drift/OLS/windows/endpoint/final means. ARRIVED binds native noWriteNow only after a completed time_end; final R2 is mandatory. Synthetic U03 window tests are separately labelled manufactured scalar data, not a native benchmark arrival.',
    'Observed near/failure U01, linear, controller, unexpected Co, mass/energy/rho relative-change and candidate/confirmed capture branches. Existing regression tests cover StageLedger/evaluator/NaN failures across ACK. Flush last16-stage raw and event; arrival also captures current R2. Maximum16 raw bursts is fail-closed, no silent overflow. Relative-change alarms are operational only; mass/energy remain DIAGNOSTIC_ONLY_WITH_REGISTERED_INTERPRETATION.',
    'RUNNING→VALIDATING requires a completed native stream, then actual required-artifact validation; all checks PASS before SEALED. Dry-run validates immutable seal and moves to PURGE_ELIGIBLE. Explicit authorized unlink of only the exact allowlist creates PURGED. Failed validation cannot seal; interruption does not auto resume.',
    'Independent required_retention() classifies R0 histories/logs/inputs/code/statistics/manifests; R1 selected full/raw/replay/pressure/rho/mass/energy/anomaly audit; R2 initial/startup/development/intermediate/arrival/final snapshots; R3 explicitly nonselected temporary validation/conversion copies; R4 scratch/atomic/replay workspaces. Manifest class overrides for required R0/R1/R2 are rejected.',
    'Archive exact registered input/source/instrumentation/analysis files and hashed contract/mesh/binary/library/compiler/platform provenance documents, seal raw logs and histories, reproduce selected59 audit, validate fields and final statistics. Production provenance documents must be retained R0. Exclusive fsynced seal publication captures case/Co/start-end/all category SHA/validation/must-retain/purge paths. Seal is never edited in place.',
    'Only registered future diagnostic-series roots or newly created lifecycle_test synthetic roots. Flat exact paths, no traversal/directories/symlinks/hardlink sharing; root private and quiescent. Entire allowlist SHA/size/core verification before unlink, dry-run ID and explicit user authorization ID required. Recheck file before deletion, append fsynced hash-chain INTENT/DELETED/COMPLETED journal with UTC/bytes/seal/auth. Partial/interrupted journal rejects verification/resume; requires manual audited recovery. No rm-rf or capacity-triggered deletion.',
    'R3 may be regenerated by same registered setup, but original R0/R1/R2 remain. Hashes of deleted data attest historical integrity and cannot recreate/reanalyse content. Compiler/CPU/libraries/FP order/OS/parallelism preclude a promised bitwise rerun. New questions requiring unretained full-field/nonselected matrix history may require new computation.',
    'All7 full selected audit steps, up to56 selected/trigger terminal bundles, initial/final and505 upper-bound scientific snapshots per series remain permanent under inherited scheduling and trigger reserve. Boundary/reference/mass/sync/energy audit data are retained R1. Multiple candidate/confirmed fields provide arrival-region evidence; their actual current-step time is stored without dt alignment. Complete receipts/primary histories and logs cannot be purged.',
    'Run Co0.5, validate, seal, explicit dry-run/authorize/purge only temporary copies, verify permanent evidence, then separately preflight Co0.25. Future launcher requires verified PURGED prior production seals and measures their retained bytes. Permanent R0/R1/R2 accumulates; only heavy temporary/scratch occupancy is released.',
    'C3 >0.5percent trigger unchanged. STOP before any Co0.125 execution, measure actual retained/free, separate resource review and explicit authorization. ModelA allunpurged upper bound, ModelB firstpurged and ModelC bothpurged are provided. At worst-case t*=2, even ModelC838611250408B exceeds initial795726016512B free; earlier arrival may change actual footprint, never auto-authorize.',
    'PASS: new synthetic native evidence copies + separately labelled constant scalar-window fixture; generate temporary copies, actual native replay/history/log checks, immutable seal, dry-run, authorized synthetic-only purge and verify. Reclaimed3276800B from two newly generated copies. Native fixture does not generate a CFD case or write a mesh.',
    'PASS fail-closed: missing/invalid seal, unknown file, R0/R1/R2 marked, symlink escape, traversal, changed after seal/dry-run, missing validation, partial deletion, interrupted INTENT journal, no automatic resume, missing authorization and outside registered root. Exact failure reasons stored in lifecycle_validation.json.',
    'After purge, original seal bytes unchanged, all retained core hashes PASS, selected59 native replay PASS and endpoint scalar/final synthetic-window analysis reproduce. Independently recomputed six primary QoIs from retained R2 final state plus retained R0 native geometry agree exactly with recorded history. SeriesB created afterA purge; comparison uses only retained R0 scalar means and preserves C3 trigger. Fields/raw audits R1/R2 remain independently available. Synthetic provenance is labelled test identity; actual native build/source/code provenance separately retained.',
    'Fresh classification sums: Co0.5 permanent178636906968B (178.64GB), Co0.25 permanent250017072048B (250.02GB), main total428653979016B. Working peak195816776152B/267196941232B respectively; sequential main peak445833848200B (56.03percent initialfree). Co0.125 permanent392777402208B; after firsttwo purge total peak838611250408B (105.39percent initialfree). R3+R4 share16GiB maximum; actual reclaim equals sealed allowlist size, not guaranteed16GiB. v1.3 already avoids disk writes for nonselected raw; no nonexistent payload reclaim credit. Original394GB referred to two-series total, not one-series permanent.',
    'AS8GiB native +8GiB backend, ≥24GiB MemAvailable preflight; existing bounded ring/bundle/chunk/packet + new16MiB primary chunk and last5 primitive outer states/bounded arrival history. Target production RSS/temporary JSON throughput and I/O latency remain UNRESOLVED. Native/synthetic log byte ordering/receipt/replay tests PASS; these are not production throughput measurements.',
    'UNRESOLVED. No production/pilot timing.24 outer/2pressure/0nonorthogonal unchanged. Next compute review must account for all145 native fv solves/169 scalar components per step plus synchronous evaluator/primary/sampling/log overhead and actual target-grid memory/I/O.',
    'Newv1.4 follows immutable versioned contract convention; preserves suppliedv1.3 SHA and full source/evidence history. Parentv1.2 authority remains unchanged. Finalv1.4 pins implementation and replacement-library SHA separately from the frozen native semantic source/instrumentation identities. Binding/lifecycle closure does not authorize execution.',
    'Scientifically allowed/technically ready inherited YES; storage-ready YES under primary planning caps. Resource-ready NO because target memory/I/O/compute remain unresolved. Conditional third-series worst-case storage infeasible on current disk. Formal GateJ forbidden/notexecuted/not evaluated; GateF FAIL, allRa needs320, downstream/particles NO.',
    'NEXT_SINGLE_TASK=REVIEW_ROUTE_A_DIAGNOSTIC_TRANSIENT_COMPUTE_FEASIBILITY; recommendedgpt-6.1-sol /medium. User decision required before the next task, no execution or future actual purge authorized by this FIX.'
    ]
    sections=[{'number':i+1,'title':name,'finding':text} for i,(name,text) in enumerate(zip(headings,texts))]
    report={'task':'FIX_ROUTE_A_DIAGNOSTIC_TRANSIENT_RESOURCE_REVISION','status':status,'sections':sections,'capacity':capacity,'tests':tests,'authority_verification':start['authority_sha256'],'protected_files_unchanged':True,'invariants':invariant,'final_contract_sha256':sha(target),'final_contract_path':str(target),'implementation_sha256':sources,'planning_numbers_not_measurements':True}
    write(PREP/'DiagnosticTransient_resource_revision_fix.json',report)
    md='# DiagnosticTransient resource revision FIX\n\n'+ '\n\n'.join(f"## {s['number']}. {s['title']}\n\n{s['finding']}" for s in sections)
    md+='\n\n### Per-series planning caps (decimal GB)\n\n| Co | Working peak | Permanent after seal/purge | Shared temporary cap |\n|---|---:|---:|---:|\n'+''.join(f"| {co} | {v['working_peak_bytes']/1e9:.3f} | {v['permanent_bytes']/1e9:.3f} | ≤17.180 |\n" for co,v in capacity['series'].items())
    md+='\nFinal contract SHA-256: `'+sha(target)+'`.\n\n```text\n'+'\n'.join(f'{k} = {v}' for k,v in status.items())+'\n```\n'
    (PREP/'DiagnosticTransient_resource_revision_fix.md').write_text(md)
    (R/'docs/routeA_diagnostic_transient_contract_v1.4.md').write_text('# Route A diagnostic transient contractv1.4\n\nPersistence/binding/lifecycle FIX finalized. Parentv1.2 and incompletev1.3 candidate are immutable authorities. Scientific/numerical definitions are unchanged. Production execution is disabled until memory/I/O/compute resource review and explicit user authorization.\n\nCanonical machine authority: `routeA_diagnostic_transient_contract_v1.4.json`; SHA sidecar pins exact bytes.\n\n'+md)
    states=[{'state':k,'entry_rule':v,'purge_allowed':p} for k,v,p in [('RUNNING','Registered preflight and pinned new series; collect every required callback','NO'),('VALIDATING','Native run complete; validate all required artifacts','NO'),('SEALED','All required checks PASS; immutable seal published','NO'),('PURGE_ELIGIBLE','Valid seal and hash/allowlist dry-run','ONLY_WITH_EXPLICIT_USER_AUTHORIZATION'),('PURGED','Exact unlink allowlist complete; retained integrity and journal verify','COMPLETED_NO_AUTO_RESUME')]]
    with (PREP/'DiagnosticTransient_evidence_lifecycle.csv').open('w',newline='') as f:w=csv.DictWriter(f,fieldnames=list(states[0]));w.writeheader();w.writerows(states)
    write(PREP/'DiagnosticTransient_purge_policy.json',{'allowlist_only':True,'valid_seal_required':True,'dry_run_required':True,'explicit_user_authorization_required':True,'never_delete_classes':['R0','R1','R2'],'eligible_classes':['R3','R4'],'shared_temp_cap_bytes':16*2**30,'no_recursive_directory_deletion':True,'no_auto_purge_on_capacity_failure':True,'no_auto_resume_interrupted_purge':True,'journal_permanent':True,'registered_roots':['results/routeA/diagnostic_transient/diagnostic_attempt_001/series/<case>','preparation/resource_revision_fix/lifecycle_test*/<fixture>'],'current_scope':'Only newly created synthetic fixture deletion authorized','deleted_hash_limit':'Integrity evidence only; payload unavailable','bitwise_rerun_guaranteed':False})
    write(OUT/'final_integrity.json',{'status':'PASS','protected_files_unchanged':True,'invariants':invariant,'contract_sha256':sha(target),'HEAD_known_unchanged':True})
    print(json.dumps({'status':'COMPLETE','contract_sha256':sha(target),'next_task':status['NEXT_SINGLE_TASK']},indent=2))
if __name__=='__main__':main('--draft' in sys.argv)
